# Test BayesCard

This notebook connects BayesCard (pure BN path) to the existing experiment system.

- Reuses `experiment/BayesCardRunner.py` for training and inference orchestration
- Outputs to `experiment/checkpoint/BayesCard/`
- First evaluates feasibility for four benchmarks, then executes only supported ones

In [1]:
from pathlib import Path
import sys
import pandas as pd

PROJECT_ROOT = (Path.cwd().parent if (Path.cwd().parent / 'Benchmark').exists() else Path.cwd()).resolve()
EXPERIMENT_DIR = PROJECT_ROOT / 'experiment'
CHECKPOINT_DIR = EXPERIMENT_DIR / 'checkpoint' / 'BayesCard'

sys.path.insert(0, str(EXPERIMENT_DIR))
from BayesCardRunner import BayesCardRunner

runner = BayesCardRunner(PROJECT_ROOT)
CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)

print(f'PROJECT_ROOT={PROJECT_ROOT}')
print(f'CHECKPOINT_DIR={CHECKPOINT_DIR}')

/home/liwei/miniconda3/envs/TestEnv/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/liwei/miniconda3/envs/TestEnv/lib/python3.10/site-packages/google/api_core/_python_version_support.py:275: FutureWarning: You are using a Python version (3.10.4) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)
/home/liwei/miniconda3/envs/TestEnv/lib/python3.10/site-packages/pgmpy/utils/utils.py:4: FutureWarning:

All support for the `google.generativeai` package has ended. It will no longer be receiving
updates or bug fixes. Please switch to the `google.genai` package as soon as possible.
See README for more details:

https://github.com/google-gemini/deprecated-generative-ai-python/blob/main/README.md

  import google.generativeai as genai

PROJECT_ROOT=/home/liwei/starce-final/StarCE
CHECKPOINT_DIR=/home/liwei/starce-final/StarCE/experiment/checkpoint/BayesCard

In [2]:
ALL_BENCHMARKS = ['STATS', 'JOBLight', 'JOBLightRanges', 'JOBM', 'StatsJoin']
SEED = 0

capability_rows = []
for benchmark in ALL_BENCHMARKS:
    supported, reason = runner.evaluate_benchmark_capability(benchmark)
    capability_rows.append(
        {
            'benchmark': benchmark,
            'supported_by_pure_bayescard_bn': supported,
            'reason': reason,
        }
    )

capability_df = pd.DataFrame(capability_rows)
capability_df

,benchmark,supported_by_pure_bayescard_bn,reason
0,STATS,True,Supported: can follow the pure BayesCard train...
1,JOBLight,True,Supported: can follow the pure BayesCard train...
2,JOBLightRanges,True,Supported: can follow the pure BayesCard train...
3,JOBM,False,Does not support pure BayesCard: JOBM's reliab...
4,StatsJoin,True,"Supported: reuses STATS BN model, inference on..."

## Execute

Only execute supported benchmarks below (`STATS`, `JOBLight`, `JOBLightRanges`, `StatsJoin`).

`JOBM` in the current repo relies on sampling for the reliable path, not pure BayesCard/BN, this notebook does not execute it.
`StatsJoin` reuses STATS BN model, inference only, no training.

In [3]:
BENCHMARKS_TO_RUN = [
    row['benchmark']
    for row in capability_rows
    if row['supported_by_pure_bayescard_bn']
]

summary_df = runner.run_all(BENCHMARKS_TO_RUN, seed=SEED, force_retrain=True)
summary_df

INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table badges
INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table badges
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table badges
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table badges
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table badges are ['Id', 'UserId', 'Date']
INFO:DataPrepare.prepare_single_tables:NULL values for table badges are [-145430.05460150907, -118638.27789238832, -83944821.66928385]

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['badges.Id', 'badges.UserId', 'badges.Date'], dtype='object')
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['badges.Id', 'badges.UserId', 'badges.Date'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table badges
INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table votes
INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table votes
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table votes
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table votes
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table votes are ['Id', 'PostId', 'VoteTypeId', 'CreationDate', 'UserId', 'BountyAmount']
INFO:DataPrepare.prepare_single_tables:NULL values for table votes are [-291496.65403642703, -140805.12052162504, -100002.72127330764, -76489038.65597203, -114338.12160392365, -100067.34528348624]
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table votes
INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table postHistory

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['votes.Id', 'votes.PostId', 'votes.VoteTypeId', 'votes.CreationDate',
       'votes.UserId', 'votes.BountyAmount'],
      dtype='object')
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['votes.Id', 'votes.PostId', 'votes.VoteTypeId', 'votes.CreationDate',
       'votes.UserId', 'votes.BountyAmount'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table postHistory
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table postHistory
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table postHistory
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table postHistory are ['Id', 'PostHistoryTypeId', 'PostId', 'CreationDate', 'UserId']
INFO:DataPrepare.prepare_single_tables:NULL values for table postHistory are [-288489.2569744702, -100004.90864489143, -156538.34982805562, -82263706.33163796, -116035.05473015195]
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table postHistory
INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table posts
INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table posts
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table posts
INFO:DataPrepare.prepare_single_tables:Preparing multiplier comments.PostId = posts.Id for table posts

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['postHistory.Id', 'postHistory.PostHistoryTypeId', 'postHistory.PostId',
       'postHistory.CreationDate', 'postHistory.UserId'],
      dtype='object')
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['postHistory.Id', 'postHistory.PostHistoryTypeId', 'postHistory.PostId',
       'postHistory.CreationDate', 'postHistory.UserId'],
      dtype='object')
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['posts.Id', 'posts.PostTypeId', 'posts.CreationDate', 'posts.Score',
       'posts.ViewCount', 'posts.OwnerUserId', 'posts.AnswerCount',
       'posts.CommentCount', 'posts.FavoriteCount'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing multiplier tags.ExcerptPostId = posts.Id for table posts

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['comments.Id', 'comments.PostId', 'comments.Score',
       'comments.CreationDate', 'comments.UserId'],
      dtype='object')
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['tags.Id', 'tags.Count', 'tags.ExcerptPostId'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing multiplier postLinks.PostId = posts.Id for table posts
INFO:DataPrepare.prepare_single_tables:Preparing multiplier postLinks.RelatedPostId = posts.Id for table posts

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['postLinks.Id', 'postLinks.CreationDate', 'postLinks.PostId',
       'postLinks.RelatedPostId', 'postLinks.LinkTypeId'],
      dtype='object')
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['postLinks.Id', 'postLinks.CreationDate', 'postLinks.PostId',
       'postLinks.RelatedPostId', 'postLinks.LinkTypeId'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing multiplier postHistory.PostId = posts.Id for table posts

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['postHistory.Id', 'postHistory.PostHistoryTypeId', 'postHistory.PostId',
       'postHistory.CreationDate', 'postHistory.UserId'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing multiplier votes.PostId = posts.Id for table posts

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['votes.Id', 'votes.PostId', 'votes.VoteTypeId', 'votes.CreationDate',
       'votes.UserId', 'votes.BountyAmount'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table posts
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table posts are ['Id', 'PostTypeId', 'CreationDate', 'Score', 'ViewCount', 'OwnerUserId', 'AnswerCount', 'CommentCount', 'FavoriteCount', 'mul_comments.PostId', 'mul_comments.PostId_nn', 'mul_tags.ExcerptPostId', 'mul_tags.ExcerptPostId_nn', 'mul_postLinks.PostId', 'mul_postLinks.PostId_nn', 'mul_postLinks.RelatedPostId', 'mul_postLinks.RelatedPostId_nn', 'mul_postHistory.PostId', 'mul_postHistory.PostId_nn', 'mul_votes.PostId', 'mul_votes.PostId_nn']
INFO:DataPrepare.prepare_single_tables:NULL values for table posts are [-156147.69956507784, -100001.56896579107, -80434549.10171346, -100002.79200223536, -100565.74612176091, -116546.76482666255, -100001.1127255213, -100001.89521394277, -100002.5435848256, -100001.89521394277, -100002.31443199965, -100000.0065799513, -100001.0001, -100000.12080540141, -100001.03813166043, -100000.12080540141, -100001.06451897886, -100003.29647079238, -100003.29647079238, -100003.56694352439, -100003.73158430026]
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table posts
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table posts and relationship comments.PostId = posts.Id

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['posts.Id', 'posts.PostTypeId', 'posts.CreationDate', 'posts.Score',
       'posts.ViewCount', 'posts.OwnerUserId', 'posts.AnswerCount',
       'posts.CommentCount', 'posts.FavoriteCount',
       'posts.mul_comments.PostId', 'posts.mul_comments.PostId_nn',
       'posts.mul_tags.ExcerptPostId', 'posts.mul_tags.ExcerptPostId_nn',
       'posts.mul_postLinks.PostId', 'posts.mul_postLinks.PostId_nn',
       'posts.mul_postLinks.RelatedPostId',
       'posts.mul_postLinks.RelatedPostId_nn', 'posts.mul_postHistory.PostId',
       'posts.mul_postHistory.PostId_nn', 'posts.mul_votes.PostId',
       'posts.mul_votes.PostId_nn'],
      dtype='object')
====================================
Index(['posts.Id', 'posts.PostTypeId', 'posts.CreationDate', 'posts.Score',
       'posts.ViewCount', 'posts.OwnerUserId', 'posts.AnswerCount',
       'posts.CommentCount', 'posts.FavoriteCount',
       'posts.mul_comments.PostId', 'posts.mul_comments.PostId_nn',
       'posts.mul_tags.ExcerptPostId', 'posts.mul_tags.ExcerptPostId_nn',
       'posts.mul_postLinks.PostId', 'posts.mul_postLinks.PostId_nn',
       'posts.mul_postLinks.RelatedPostId',
       'posts.mul_postLinks.RelatedPostId_nn', 'posts.mul_postHistory.PostId',
       'posts.mul_postHistory.PostId_nn', 'posts.mul_votes.PostId',
       'posts.mul_votes.PostId_nn'],
      dtype='object') posts.Id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['comments.Id', 'comments.PostId', 'comments.Score',
       'comments.CreationDate', 'comments.UserId'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table posts and relationship tags.ExcerptPostId = posts.Id
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table posts and relationship postLinks.PostId = posts.Id

====================================
Index(['posts.Id', 'posts.PostTypeId', 'posts.CreationDate', 'posts.Score',
       'posts.ViewCount', 'posts.OwnerUserId', 'posts.AnswerCount',
       'posts.CommentCount', 'posts.FavoriteCount',
       'posts.mul_comments.PostId', 'posts.mul_comments.PostId_nn',
       'posts.mul_tags.ExcerptPostId', 'posts.mul_tags.ExcerptPostId_nn',
       'posts.mul_postLinks.PostId', 'posts.mul_postLinks.PostId_nn',
       'posts.mul_postLinks.RelatedPostId',
       'posts.mul_postLinks.RelatedPostId_nn', 'posts.mul_postHistory.PostId',
       'posts.mul_postHistory.PostId_nn', 'posts.mul_votes.PostId',
       'posts.mul_votes.PostId_nn'],
      dtype='object') posts.Id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['tags.Id', 'tags.Count', 'tags.ExcerptPostId'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table posts and relationship postLinks.RelatedPostId = posts.Id

====================================
Index(['posts.Id', 'posts.PostTypeId', 'posts.CreationDate', 'posts.Score',
       'posts.ViewCount', 'posts.OwnerUserId', 'posts.AnswerCount',
       'posts.CommentCount', 'posts.FavoriteCount',
       'posts.mul_comments.PostId', 'posts.mul_comments.PostId_nn',
       'posts.mul_tags.ExcerptPostId', 'posts.mul_tags.ExcerptPostId_nn',
       'posts.mul_postLinks.PostId', 'posts.mul_postLinks.PostId_nn',
       'posts.mul_postLinks.RelatedPostId',
       'posts.mul_postLinks.RelatedPostId_nn', 'posts.mul_postHistory.PostId',
       'posts.mul_postHistory.PostId_nn', 'posts.mul_votes.PostId',
       'posts.mul_votes.PostId_nn'],
      dtype='object') posts.Id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['postLinks.Id', 'postLinks.CreationDate', 'postLinks.PostId',
       'postLinks.RelatedPostId', 'postLinks.LinkTypeId'],
      dtype='object')
====================================
Index(['posts.Id', 'posts.PostTypeId', 'posts.CreationDate', 'posts.Score',
       'posts.ViewCount', 'posts.OwnerUserId', 'posts.AnswerCount',
       'posts.CommentCount', 'posts.FavoriteCount',
       'posts.mul_comments.PostId', 'posts.mul_comments.PostId_nn',
       'posts.mul_tags.ExcerptPostId', 'posts.mul_tags.ExcerptPostId_nn',
       'posts.mul_postLinks.PostId', 'posts.mul_postLinks.PostId_nn',
       'posts.mul_postLinks.RelatedPostId',
       'posts.mul_postLinks.RelatedPostId_nn', 'posts.mul_postHistory.PostId',
       'posts.mul_postHistory.PostId_nn', 'posts.mul_votes.PostId',
       'posts.mul_votes.PostId_nn'],
      dtype='object') posts.Id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['postLinks.Id', 'postLinks.CreationDate', 'postLinks.PostId',
       'postLinks.RelatedPostId', 'postLinks.LinkTypeId'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table posts and relationship postHistory.PostId = posts.Id

====================================
Index(['posts.Id', 'posts.PostTypeId', 'posts.CreationDate', 'posts.Score',
       'posts.ViewCount', 'posts.OwnerUserId', 'posts.AnswerCount',
       'posts.CommentCount', 'posts.FavoriteCount',
       'posts.mul_comments.PostId', 'posts.mul_comments.PostId_nn',
       'posts.mul_tags.ExcerptPostId', 'posts.mul_tags.ExcerptPostId_nn',
       'posts.mul_postLinks.PostId', 'posts.mul_postLinks.PostId_nn',
       'posts.mul_postLinks.RelatedPostId',
       'posts.mul_postLinks.RelatedPostId_nn', 'posts.mul_postHistory.PostId',
       'posts.mul_postHistory.PostId_nn', 'posts.mul_votes.PostId',
       'posts.mul_votes.PostId_nn'],
      dtype='object') posts.Id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['postHistory.Id', 'postHistory.PostHistoryTypeId', 'postHistory.PostId',
       'postHistory.CreationDate', 'postHistory.UserId'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table posts and relationship votes.PostId = posts.Id

====================================
Index(['posts.Id', 'posts.PostTypeId', 'posts.CreationDate', 'posts.Score',
       'posts.ViewCount', 'posts.OwnerUserId', 'posts.AnswerCount',
       'posts.CommentCount', 'posts.FavoriteCount',
       'posts.mul_comments.PostId', 'posts.mul_comments.PostId_nn',
       'posts.mul_tags.ExcerptPostId', 'posts.mul_tags.ExcerptPostId_nn',
       'posts.mul_postLinks.PostId', 'posts.mul_postLinks.PostId_nn',
       'posts.mul_postLinks.RelatedPostId',
       'posts.mul_postLinks.RelatedPostId_nn', 'posts.mul_postHistory.PostId',
       'posts.mul_postHistory.PostId_nn', 'posts.mul_votes.PostId',
       'posts.mul_votes.PostId_nn'],
      dtype='object') posts.Id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['votes.Id', 'votes.PostId', 'votes.VoteTypeId', 'votes.CreationDate',
       'votes.UserId', 'votes.BountyAmount'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table users
INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table users
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table users
INFO:DataPrepare.prepare_single_tables:Preparing multiplier comments.UserId = users.Id for table users
INFO:DataPrepare.prepare_single_tables:Preparing multiplier badges.UserId = users.Id for table users

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['users.Id', 'users.Reputation', 'users.CreationDate', 'users.Views',
       'users.UpVotes', 'users.DownVotes'],
      dtype='object')
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['comments.Id', 'comments.PostId', 'comments.Score',
       'comments.CreationDate', 'comments.UserId'],
      dtype='object')
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['badges.Id', 'badges.UserId', 'badges.Date'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing multiplier postHistory.UserId = users.Id for table users
INFO:DataPrepare.prepare_single_tables:Preparing multiplier votes.UserId = users.Id for table users

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['postHistory.Id', 'postHistory.PostHistoryTypeId', 'postHistory.PostId',
       'postHistory.CreationDate', 'postHistory.UserId'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing multiplier posts.OwnerUserId = users.Id for table users

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['votes.Id', 'votes.PostId', 'votes.VoteTypeId', 'votes.CreationDate',
       'votes.UserId', 'votes.BountyAmount'],
      dtype='object')
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['posts.Id', 'posts.PostTypeId', 'posts.CreationDate', 'posts.Score',
       'posts.ViewCount', 'posts.OwnerUserId', 'posts.AnswerCount',
       'posts.CommentCount', 'posts.FavoriteCount'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table users
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table users are ['Id', 'Reputation', 'CreationDate', 'Views', 'UpVotes', 'DownVotes', 'mul_comments.UserId', 'mul_comments.UserId_nn', 'mul_badges.UserId', 'mul_badges.UserId_nn', 'mul_postHistory.UserId', 'mul_postHistory.UserId_nn', 'mul_votes.UserId', 'mul_votes.UserId_nn', 'mul_posts.OwnerUserId', 'mul_posts.OwnerUserId_nn']
INFO:DataPrepare.prepare_single_tables:NULL values for table users are [-128037.39982721637, -100084.07883527588, -87026451.76027359, -100008.90973422195, -100006.58755195288, -100000.26100514569, -100004.25230086794, -100004.91387557346, -100001.98028598884, -100002.35838890266, -100006.98978381896, -100007.44156311221, -100000.86281543707, -100001.72535728457, -100002.2464484191, -100002.70130272783]
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table users
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table users and relationship comments.UserId = users.Id

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['users.Id', 'users.Reputation', 'users.CreationDate', 'users.Views',
       'users.UpVotes', 'users.DownVotes', 'users.mul_comments.UserId',
       'users.mul_comments.UserId_nn', 'users.mul_badges.UserId',
       'users.mul_badges.UserId_nn', 'users.mul_postHistory.UserId',
       'users.mul_postHistory.UserId_nn', 'users.mul_votes.UserId',
       'users.mul_votes.UserId_nn', 'users.mul_posts.OwnerUserId',
       'users.mul_posts.OwnerUserId_nn'],
      dtype='object')
====================================
Index(['users.Id', 'users.Reputation', 'users.CreationDate', 'users.Views',
       'users.UpVotes', 'users.DownVotes', 'users.mul_comments.UserId',
       'users.mul_comments.UserId_nn', 'users.mul_badges.UserId',
       'users.mul_badges.UserId_nn', 'users.mul_postHistory.UserId',
       'users.mul_postHistory.UserId_nn', 'users.mul_votes.UserId',
       'users.mul_votes.UserId_nn', 'users.mul_posts.OwnerUserId',
       'users.mul_posts.OwnerUserId_nn'],
      dtype='object') users.Id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['comments.Id', 'comments.PostId', 'comments.Score',
       'comments.CreationDate', 'comments.UserId'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table users and relationship badges.UserId = users.Id
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table users and relationship postHistory.UserId = users.Id

====================================
Index(['users.Id', 'users.Reputation', 'users.CreationDate', 'users.Views',
       'users.UpVotes', 'users.DownVotes', 'users.mul_comments.UserId',
       'users.mul_comments.UserId_nn', 'users.mul_badges.UserId',
       'users.mul_badges.UserId_nn', 'users.mul_postHistory.UserId',
       'users.mul_postHistory.UserId_nn', 'users.mul_votes.UserId',
       'users.mul_votes.UserId_nn', 'users.mul_posts.OwnerUserId',
       'users.mul_posts.OwnerUserId_nn'],
      dtype='object') users.Id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['badges.Id', 'badges.UserId', 'badges.Date'], dtype='object')
====================================
Index(['users.Id', 'users.Reputation', 'users.CreationDate', 'users.Views',
       'users.UpVotes', 'users.DownVotes', 'users.mul_comments.UserId',
       'users.mul_comments.UserId_nn', 'users.mul_badges.UserId',
       'users.mul_badges.UserId_nn', 'users.mul_postHistory.UserId',
       'users.mul_postHistory.UserId_nn', 'users.mul_votes.UserId',
       'users.mul_votes.UserId_nn', 'users.mul_posts.OwnerUserId',
       'users.mul_posts.OwnerUserId_nn'],
      dtype='object') users.Id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['postHistory.Id', 'postHistory.PostHistoryTypeId', 'postHistory.PostId',
       'postHistory.CreationDate', 'postHistory.UserId'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table users and relationship votes.UserId = users.Id

====================================
Index(['users.Id', 'users.Reputation', 'users.CreationDate', 'users.Views',
       'users.UpVotes', 'users.DownVotes', 'users.mul_comments.UserId',
       'users.mul_comments.UserId_nn', 'users.mul_badges.UserId',
       'users.mul_badges.UserId_nn', 'users.mul_postHistory.UserId',
       'users.mul_postHistory.UserId_nn', 'users.mul_votes.UserId',
       'users.mul_votes.UserId_nn', 'users.mul_posts.OwnerUserId',
       'users.mul_posts.OwnerUserId_nn'],
      dtype='object') users.Id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['votes.Id', 'votes.PostId', 'votes.VoteTypeId', 'votes.CreationDate',
       'votes.UserId', 'votes.BountyAmount'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table users and relationship posts.OwnerUserId = users.Id

====================================
Index(['users.Id', 'users.Reputation', 'users.CreationDate', 'users.Views',
       'users.UpVotes', 'users.DownVotes', 'users.mul_comments.UserId',
       'users.mul_comments.UserId_nn', 'users.mul_badges.UserId',
       'users.mul_badges.UserId_nn', 'users.mul_postHistory.UserId',
       'users.mul_postHistory.UserId_nn', 'users.mul_votes.UserId',
       'users.mul_votes.UserId_nn', 'users.mul_posts.OwnerUserId',
       'users.mul_posts.OwnerUserId_nn'],
      dtype='object') users.Id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['posts.Id', 'posts.PostTypeId', 'posts.CreationDate', 'posts.Score',
       'posts.ViewCount', 'posts.OwnerUserId', 'posts.AnswerCount',
       'posts.CommentCount', 'posts.FavoriteCount'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table comments
INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table comments
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table comments
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table comments
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table comments are ['Id', 'PostId', 'Score', 'CreationDate', 'UserId']
INFO:DataPrepare.prepare_single_tables:NULL values for table comments are [-207695.613691119, -154243.58119061703, -100000.38856275208, -80632241.25169347, -112443.05547411792]
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table comments
INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table postLinks
INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table postLinks
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table postLinks
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table postLinks
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table postLinks are ['Id', 'CreationDate', 'PostId', 'RelatedPostId', 'LinkTypeId']
INFO:DataPrepare.prepare_single_tables:NULL values for table postLinks are [-2426833.610440479, -88842296.2054684, -160227.76797966132, -132982.60548641687, -100001.16511531256]
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table postLinks
INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table tags
INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table tags
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table tags
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table tags
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table tags are ['Id', 'Count', 'ExcerptPostId']
INFO:DataPrepare.prepare_single_tables:NULL values for table tags are [-100952.36734806202, -100114.00785193799, -154505.44305302014]
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table tags

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['comments.Id', 'comments.PostId', 'comments.Score',
       'comments.CreationDate', 'comments.UserId'],
      dtype='object')
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['comments.Id', 'comments.PostId', 'comments.Score',
       'comments.CreationDate', 'comments.UserId'],
      dtype='object')
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['postLinks.Id', 'postLinks.CreationDate', 'postLinks.PostId',
       'postLinks.RelatedPostId', 'postLinks.LinkTypeId'],
      dtype='object')
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['postLinks.Id', 'postLinks.CreationDate', 'postLinks.PostId',
       'postLinks.RelatedPostId', 'postLinks.LinkTypeId'],
      dtype='object')
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['tags.Id', 'tags.Count', 'tags.ExcerptPostId'], dtype='object')
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['tags.Id', 'tags.Count', 'tags.ExcerptPostId'], dtype='object')

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 1.480471134185791 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 212863.0 rows and 16 cols

Discretizing table takes 1.4818150997161865 secs

INFO:Models.BN_single_model:Structure learning took 5.5114147663116455 secs.
INFO:Models.Bayescard_BN:Model spec[('posts.ViewCount', 'posts.CreationDate'), ('posts.mul_votes.PostId', 'posts.Score'), ('posts.AnswerCount', 'posts.ViewCount'), ('posts.PostTypeId', 'posts.AnswerCount'), ('comments.CreationDate', 'posts.CommentCount'), ('posts.ViewCount', 'posts.FavoriteCount'), ('posts.CommentCount', 'posts.mul_comments.PostId_nn'), ('posts.PostTypeId', 'posts.mul_tags.ExcerptPostId'), ('posts.ViewCount', 'posts.mul_postLinks.PostId'), ('posts.ViewCount', 'posts.mul_postLinks.RelatedPostId'), ('posts.ViewCount', 'posts.mul_postHistory.PostId'), ('posts.FavoriteCount', 'posts.mul_votes.PostId'), ('comments.Score', 'comments.comments_nn'), ('posts.CommentCount', 'comments.Score'), ('posts.CreationDate', 'comments.CreationDate')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 5.512670278549194 secs.

INFO:Models.Bayescard_BN:done, took 5.1042561531066895 secs.
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/DataPrepare/join_data_preparation.py:487: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  df_samples = df_samples.merge(next_table_data, how='left', right_index=True,

done, parameter learning took 5.1057000160217285 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 5.289424180984497 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 200982.99999999997 rows and 14 cols

Discretizing table takes 5.290808916091919 secs

INFO:Models.BN_single_model:Structure learning took 3.9004220962524414 secs.
INFO:Models.Bayescard_BN:Model spec[('users.Views', 'users.Reputation'), ('users.Views', 'users.CreationDate'), ('users.users_nn', 'users.Views'), ('users.Reputation', 'users.UpVotes'), ('users.UpVotes', 'users.DownVotes'), ('users.mul_posts.OwnerUserId', 'users.mul_comments.UserId_nn'), ('users.Reputation', 'users.mul_badges.UserId'), ('users.mul_posts.OwnerUserId', 'users.mul_postHistory.UserId'), ('users.UpVotes', 'users.mul_votes.UserId'), ('users.Reputation', 'users.mul_posts.OwnerUserId'), ('comments.Score', 'comments.comments_nn'), ('comments.CreationDate', 'comments.Score'), ('users.CreationDate', 'comments.CreationDate')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 3.9016711711883545 secs.

INFO:Models.Bayescard_BN:done, took 0.21694636344909668 secs.
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):

done, parameter learning took 0.21815180778503418 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 3.9001028537750244 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 95098.00000000001 rows and 12 cols

Discretizing table takes 3.901550531387329 secs

INFO:Models.BN_single_model:Structure learning took 2.6931612491607666 secs.
INFO:Models.Bayescard_BN:Model spec[('users.Views', 'users.CreationDate'), ('users.mul_badges.UserId_nn', 'users.Views'), ('users.mul_badges.UserId_nn', 'users.UpVotes'), ('users.mul_badges.UserId_nn', 'users.DownVotes'), ('users.mul_postHistory.UserId', 'users.mul_comments.UserId'), ('users.Reputation', 'users.mul_badges.UserId_nn'), ('users.mul_posts.OwnerUserId', 'users.mul_postHistory.UserId'), ('users.UpVotes', 'users.mul_votes.UserId'), ('users.Reputation', 'users.mul_posts.OwnerUserId'), ('badges.Date', 'badges.badges_nn'), ('users.CreationDate', 'badges.Date')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...
INFO:Models.Bayescard_BN:done, took 0.11310768127441406 secs.
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/DataPrepare/join_data_preparation.py:487: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  df_samples = df_samples.merge(next_table_data, how='left', right_index=True,

Structure learning took 2.6943888664245605 secs.
done, parameter learning took 0.11436009407043457 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 1.5075175762176514 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 92412.0 rows and 16 cols

Discretizing table takes 1.5094609260559082 secs

INFO:Models.BN_single_model:Structure learning took 2.95219087600708 secs.
INFO:Models.Bayescard_BN:Model spec[('posts.mul_postHistory.PostId', 'posts.PostTypeId'), ('posts.ViewCount', 'posts.CreationDate'), ('posts.mul_votes.PostId', 'posts.Score'), ('posts.AnswerCount', 'posts.ViewCount'), ('posts.PostTypeId', 'posts.AnswerCount'), ('posts.mul_postHistory.PostId', 'posts.CommentCount'), ('posts.ViewCount', 'posts.FavoriteCount'), ('posts.CommentCount', 'posts.mul_comments.PostId'), ('posts.CreationDate', 'posts.mul_tags.ExcerptPostId_nn'), ('posts.ViewCount', 'posts.mul_postLinks.PostId'), ('posts.ViewCount', 'posts.mul_postLinks.RelatedPostId'), ('posts.posts_nn', 'posts.mul_postHistory.PostId'), ('posts.FavoriteCount', 'posts.mul_votes.PostId'), ('tags.Count', 'tags.tags_nn'), ('posts.PostTypeId', 'tags.Count')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...
INFO:Models.Bayescard_BN:done, took 0.16578221321105957 secs.

Structure learning took 2.9533121585845947 secs.
done, parameter learning took 0.16675186157226562 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 1.0697495937347412 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 95474.0 rows and 16 cols

Discretizing table takes 1.0714335441589355 secs

INFO:Models.BN_single_model:Structure learning took 3.331264019012451 secs.
INFO:Models.Bayescard_BN:Model spec[('posts.ViewCount', 'posts.CreationDate'), ('posts.mul_votes.PostId', 'posts.Score'), ('posts.AnswerCount', 'posts.ViewCount'), ('posts.PostTypeId', 'posts.AnswerCount'), ('posts.mul_postHistory.PostId', 'posts.CommentCount'), ('posts.ViewCount', 'posts.FavoriteCount'), ('posts.CommentCount', 'posts.mul_comments.PostId'), ('posts.PostTypeId', 'posts.mul_tags.ExcerptPostId'), ('postLinks.LinkTypeId', 'posts.mul_postLinks.PostId_nn'), ('posts.FavoriteCount', 'posts.mul_postLinks.RelatedPostId_nn'), ('posts.ViewCount', 'posts.mul_postHistory.PostId'), ('posts.FavoriteCount', 'posts.mul_votes.PostId'), ('postLinks.LinkTypeId', 'postLinks.postLinks_nn'), ('posts.CreationDate', 'postLinks.CreationDate'), ('postLinks.CreationDate', 'postLinks.LinkTypeId')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...
INFO:Models.Bayescard_BN:done, took 0.16457772254943848 secs.

Structure learning took 3.332399368286133 secs.
done, parameter learning took 0.16584467887878418 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 1.05900239944458 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 97901.0 rows and 16 cols

Discretizing table takes 1.0603737831115723 secs

INFO:Models.BN_single_model:Structure learning took 3.0436642169952393 secs.
INFO:Models.Bayescard_BN:Model spec[('posts.ViewCount', 'posts.CreationDate'), ('posts.mul_votes.PostId', 'posts.Score'), ('posts.AnswerCount', 'posts.ViewCount'), ('posts.PostTypeId', 'posts.AnswerCount'), ('posts.mul_votes.PostId', 'posts.CommentCount'), ('posts.ViewCount', 'posts.FavoriteCount'), ('posts.CommentCount', 'posts.mul_comments.PostId'), ('posts.PostTypeId', 'posts.mul_tags.ExcerptPostId'), ('posts.ViewCount', 'posts.mul_postLinks.PostId_nn'), ('posts.FavoriteCount', 'posts.mul_postLinks.RelatedPostId_nn'), ('posts.ViewCount', 'posts.mul_postHistory.PostId'), ('posts.FavoriteCount', 'posts.mul_votes.PostId'), ('postLinks.LinkTypeId', 'postLinks.postLinks_nn'), ('postLinks.LinkTypeId', 'postLinks.CreationDate'), ('posts.mul_postLinks.RelatedPostId_nn', 'postLinks.LinkTypeId')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...
INFO:Models.Bayescard_BN:done, took 0.14740848541259766 secs.

Structure learning took 3.0446908473968506 secs.
done, parameter learning took 0.14830398559570312 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 1.6344993114471436 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 303187.0 rows and 15 cols

Discretizing table takes 1.6359210014343262 secs

INFO:Models.BN_single_model:Structure learning took 7.226667165756226 secs.
INFO:Models.Bayescard_BN:Model spec[('posts.ViewCount', 'posts.CreationDate'), ('posts.mul_votes.PostId', 'posts.Score'), ('posts.AnswerCount', 'posts.ViewCount'), ('posts.PostTypeId', 'posts.AnswerCount'), ('posts.mul_postHistory.PostId_nn', 'posts.CommentCount'), ('posts.ViewCount', 'posts.FavoriteCount'), ('posts.CommentCount', 'posts.mul_comments.PostId'), ('posts.PostTypeId', 'posts.mul_tags.ExcerptPostId'), ('posts.ViewCount', 'posts.mul_postLinks.PostId'), ('posts.ViewCount', 'posts.mul_postLinks.RelatedPostId'), ('posts.ViewCount', 'posts.mul_postHistory.PostId_nn'), ('posts.FavoriteCount', 'posts.mul_votes.PostId'), ('posts.mul_postHistory.PostId_nn', 'postHistory.PostHistoryTypeId'), ('posts.CreationDate', 'postHistory.CreationDate')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 7.227767705917358 secs.

INFO:Models.Bayescard_BN:done, took 0.30227088928222656 secs.
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/DataPrepare/join_data_preparation.py:487: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  df_samples = df_samples.merge(next_table_data, how='left', right_index=True,

done, parameter learning took 0.3032257556915283 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 6.337472438812256 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 321405.0 rows and 14 cols

Discretizing table takes 6.339274883270264 secs

INFO:Models.BN_single_model:Structure learning took 5.341246128082275 secs.
INFO:Models.Bayescard_BN:Model spec[('users.users_nn', 'users.Reputation'), ('users.UpVotes', 'users.CreationDate'), ('users.Reputation', 'users.Views'), ('users.Reputation', 'users.UpVotes'), ('users.UpVotes', 'users.DownVotes'), ('users.mul_posts.OwnerUserId', 'users.mul_comments.UserId'), ('users.Reputation', 'users.mul_badges.UserId'), ('users.mul_posts.OwnerUserId', 'users.mul_postHistory.UserId_nn'), ('users.UpVotes', 'users.mul_votes.UserId'), ('users.Reputation', 'users.mul_posts.OwnerUserId'), ('postHistory.PostHistoryTypeId', 'postHistory.postHistory_nn'), ('users.mul_postHistory.UserId_nn', 'postHistory.PostHistoryTypeId'), ('users.CreationDate', 'postHistory.CreationDate')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 5.342511177062988 secs.

INFO:Models.Bayescard_BN:done, took 0.2944605350494385 secs.

done, parameter learning took 0.29575181007385254 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 5.3857526779174805 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 343207.0 rows and 17 cols

Discretizing table takes 5.387199401855469 secs

INFO:Models.BN_single_model:Structure learning took 6.547999620437622 secs.
INFO:Models.Bayescard_BN:Model spec[('posts.mul_votes.PostId_nn', 'posts.CreationDate'), ('posts.mul_votes.PostId_nn', 'posts.Score'), ('posts.AnswerCount', 'posts.ViewCount'), ('posts.PostTypeId', 'posts.AnswerCount'), ('posts.mul_votes.PostId_nn', 'posts.CommentCount'), ('posts.ViewCount', 'posts.FavoriteCount'), ('posts.CommentCount', 'posts.mul_comments.PostId'), ('posts.PostTypeId', 'posts.mul_tags.ExcerptPostId'), ('posts.AnswerCount', 'posts.mul_postLinks.PostId'), ('posts.FavoriteCount', 'posts.mul_postLinks.RelatedPostId'), ('posts.ViewCount', 'posts.mul_postHistory.PostId'), ('posts.FavoriteCount', 'posts.mul_votes.PostId_nn'), ('votes.CreationDate', 'votes.votes_nn'), ('posts.Score', 'votes.VoteTypeId'), ('posts.CreationDate', 'votes.CreationDate'), ('votes.VoteTypeId', 'votes.BountyAmount')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 6.549304008483887 secs.

INFO:Models.Bayescard_BN:done, took 0.3829061985015869 secs.
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/DataPrepare/join_data_preparation.py:487: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  df_samples = df_samples.merge(next_table_data, how='left', right_index=True,

done, parameter learning took 0.3842742443084717 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 10.749159336090088 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 362846.0 rows and 15 cols

Discretizing table takes 10.750996589660645 secs

INFO:Models.BN_single_model:Structure learning took 2.876164674758911 secs.
INFO:Models.Bayescard_BN:Model spec[('users.UpVotes', 'users.Reputation'), ('users.Views', 'users.CreationDate'), ('users.Reputation', 'users.Views'), ('users.users_nn', 'users.UpVotes'), ('users.UpVotes', 'users.DownVotes'), ('users.mul_postHistory.UserId', 'users.mul_comments.UserId'), ('users.Reputation', 'users.mul_badges.UserId'), ('users.Reputation', 'users.mul_postHistory.UserId'), ('users.UpVotes', 'users.mul_votes.UserId_nn'), ('users.mul_postHistory.UserId', 'users.mul_posts.OwnerUserId'), ('votes.VoteTypeId', 'votes.votes_nn'), ('users.UpVotes', 'votes.VoteTypeId'), ('votes.VoteTypeId', 'votes.CreationDate'), ('votes.VoteTypeId', 'votes.BountyAmount')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 2.877499580383301 secs.

INFO:Models.Bayescard_BN:done, took 0.36788415908813477 secs.
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/DataPrepare/join_data_preparation.py:487: UserWarning: You are merging on int and float columns where the float values are not equal to their int representation.
  df_samples = df_samples.merge(next_table_data, how='left', right_index=True,

done, parameter learning took 0.36886072158813477 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 6.131171941757202 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 110318.0 rows and 25 cols

Discretizing table takes 6.132606744766235 secs

INFO:Models.BN_single_model:Structure learning took 7.1093339920043945 secs.
INFO:Models.Bayescard_BN:Model spec[('users.Views', 'users.Reputation'), ('users.Views', 'users.CreationDate'), ('users.users_nn', 'users.Views'), ('users.mul_badges.UserId', 'users.UpVotes'), ('users.UpVotes', 'users.DownVotes'), ('users.mul_posts.OwnerUserId_nn', 'users.mul_comments.UserId'), ('users.Reputation', 'users.mul_badges.UserId'), ('users.mul_posts.OwnerUserId_nn', 'users.mul_postHistory.UserId'), ('users.UpVotes', 'users.mul_votes.UserId'), ('users.mul_badges.UserId', 'users.mul_posts.OwnerUserId_nn'), ('posts.Score', 'posts.posts_nn'), ('users.mul_postHistory.UserId', 'posts.PostTypeId'), ('users.CreationDate', 'posts.CreationDate'), ('users.Reputation', 'posts.Score'), ('posts.AnswerCount', 'posts.ViewCount'), ('posts.PostTypeId', 'posts.AnswerCount'), ('posts.mul_postHistory.PostId', 'posts.CommentCount'), ('posts.ViewCount', 'posts.FavoriteCount'), ('posts.CommentCount', 'posts.mul_comments.PostId'), ('posts.PostTypeId', 'posts.mul_tags.ExcerptPostId'), ('posts.AnswerCount', 'posts.mul_postLinks.PostId'), ('posts.ViewCount', 'posts.mul_postLinks.RelatedPostId'), ('posts.PostTypeId', 'posts.mul_postHistory.PostId'), ('posts.Score', 'posts.mul_votes.PostId')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 7.11064076423645 secs.

INFO:Models.Bayescard_BN:done, took 0.2621455192565918 secs.
INFO:test_benchmark:Loaded BN model: 0_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 10_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 1_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 2_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 3_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 4_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 5_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 6_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 7_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 8_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 9_chow-liu_1.pkl
INFO:test_benchmark:Loaded 11 BN models from /home/liwei/starce-final/StarCE/experiment/checkpoint/BayesCard/models/stats

done, parameter learning took 0.26340556144714355 secs.

WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['title.id', 'title.kind_id', 'title.production_year'], dtype='object')
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_info_idx.id', 'movie_info_idx.movie_id',
       'movie_info_idx.info_type_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing multiplier movie_info.movie_id = title.id for table title
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/DataPrepare/prepare_single_tables.py:33: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_rows = pd.read_csv(table_obj.csv_file_location, header=None, escapechar='\\', encoding='utf-8',

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_info.id', 'movie_info.movie_id', 'movie_info.info_type_id'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing multiplier cast_info.movie_id = title.id for table title

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['cast_info.id', 'cast_info.movie_id', 'cast_info.role_id'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing multiplier movie_keyword.movie_id = title.id for table title

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_keyword.id', 'movie_keyword.movie_id',
       'movie_keyword.keyword_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing multiplier movie_companies.movie_id = title.id for table title

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_companies.id', 'movie_companies.movie_id',
       'movie_companies.company_id', 'movie_companies.company_type_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table title
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table title are ['id', 'kind_id', 'production_year', 'mul_movie_info_idx.movie_id', 'mul_movie_info_idx.movie_id_nn', 'mul_movie_info.movie_id', 'mul_movie_info.movie_id_nn', 'mul_cast_info.movie_id', 'mul_cast_info.movie_id_nn', 'mul_movie_keyword.movie_id', 'mul_movie_keyword.movie_id_nn', 'mul_movie_companies.movie_id', 'mul_movie_companies.movie_id_nn']
INFO:DataPrepare.prepare_single_tables:NULL values for table title are [-1364156.5001, -100004.94392536649, -101992.78876199525, -100000.54593255547, -100001.36402264879, -100005.86793593164, -100005.89146427783, -100014.33549215097, -100014.41329544423, -100001.78940843978, -100002.60082649262, -100001.03206480498, -100001.60204034597]

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['title.id', 'title.kind_id', 'title.production_year',
       'title.mul_movie_info_idx.movie_id',
       'title.mul_movie_info_idx.movie_id_nn', 'title.mul_movie_info.movie_id',
       'title.mul_movie_info.movie_id_nn', 'title.mul_cast_info.movie_id',
       'title.mul_cast_info.movie_id_nn', 'title.mul_movie_keyword.movie_id',
       'title.mul_movie_keyword.movie_id_nn',
       'title.mul_movie_companies.movie_id',
       'title.mul_movie_companies.movie_id_nn'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table title
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table title and relationship movie_info_idx.movie_id = title.id

====================================
Index(['title.id', 'title.kind_id', 'title.production_year',
       'title.mul_movie_info_idx.movie_id',
       'title.mul_movie_info_idx.movie_id_nn', 'title.mul_movie_info.movie_id',
       'title.mul_movie_info.movie_id_nn', 'title.mul_cast_info.movie_id',
       'title.mul_cast_info.movie_id_nn', 'title.mul_movie_keyword.movie_id',
       'title.mul_movie_keyword.movie_id_nn',
       'title.mul_movie_companies.movie_id',
       'title.mul_movie_companies.movie_id_nn'],
      dtype='object') title.id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_info_idx.id', 'movie_info_idx.movie_id',
       'movie_info_idx.info_type_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table title and relationship movie_info.movie_id = title.id

====================================
Index(['title.id', 'title.kind_id', 'title.production_year',
       'title.mul_movie_info_idx.movie_id',
       'title.mul_movie_info_idx.movie_id_nn', 'title.mul_movie_info.movie_id',
       'title.mul_movie_info.movie_id_nn', 'title.mul_cast_info.movie_id',
       'title.mul_cast_info.movie_id_nn', 'title.mul_movie_keyword.movie_id',
       'title.mul_movie_keyword.movie_id_nn',
       'title.mul_movie_companies.movie_id',
       'title.mul_movie_companies.movie_id_nn'],
      dtype='object') title.id

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/DataPrepare/prepare_single_tables.py:33: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_rows = pd.read_csv(table_obj.csv_file_location, header=None, escapechar='\\', encoding='utf-8',

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_info.id', 'movie_info.movie_id', 'movie_info.info_type_id'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table title and relationship cast_info.movie_id = title.id

====================================
Index(['title.id', 'title.kind_id', 'title.production_year',
       'title.mul_movie_info_idx.movie_id',
       'title.mul_movie_info_idx.movie_id_nn', 'title.mul_movie_info.movie_id',
       'title.mul_movie_info.movie_id_nn', 'title.mul_cast_info.movie_id',
       'title.mul_cast_info.movie_id_nn', 'title.mul_movie_keyword.movie_id',
       'title.mul_movie_keyword.movie_id_nn',
       'title.mul_movie_companies.movie_id',
       'title.mul_movie_companies.movie_id_nn'],
      dtype='object') title.id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['cast_info.id', 'cast_info.movie_id', 'cast_info.role_id'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table title and relationship movie_keyword.movie_id = title.id

====================================
Index(['title.id', 'title.kind_id', 'title.production_year',
       'title.mul_movie_info_idx.movie_id',
       'title.mul_movie_info_idx.movie_id_nn', 'title.mul_movie_info.movie_id',
       'title.mul_movie_info.movie_id_nn', 'title.mul_cast_info.movie_id',
       'title.mul_cast_info.movie_id_nn', 'title.mul_movie_keyword.movie_id',
       'title.mul_movie_keyword.movie_id_nn',
       'title.mul_movie_companies.movie_id',
       'title.mul_movie_companies.movie_id_nn'],
      dtype='object') title.id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_keyword.id', 'movie_keyword.movie_id',
       'movie_keyword.keyword_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table title and relationship movie_companies.movie_id = title.id

====================================
Index(['title.id', 'title.kind_id', 'title.production_year',
       'title.mul_movie_info_idx.movie_id',
       'title.mul_movie_info_idx.movie_id_nn', 'title.mul_movie_info.movie_id',
       'title.mul_movie_info.movie_id_nn', 'title.mul_cast_info.movie_id',
       'title.mul_cast_info.movie_id_nn', 'title.mul_movie_keyword.movie_id',
       'title.mul_movie_keyword.movie_id_nn',
       'title.mul_movie_companies.movie_id',
       'title.mul_movie_companies.movie_id_nn'],
      dtype='object') title.id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_companies.id', 'movie_companies.movie_id',
       'movie_companies.company_id', 'movie_companies.company_type_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table movie_info_idx
INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table movie_info_idx
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table movie_info_idx
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table movie_info_idx
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table movie_info_idx are ['id', 'movie_id', 'info_type_id']
INFO:DataPrepare.prepare_single_tables:NULL values for table movie_info_idx are [-790018.0001, -1691796.733549514, -100100.00236805841]
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table movie_info_idx
INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table movie_info

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_info_idx.id', 'movie_info_idx.movie_id',
       'movie_info_idx.info_type_id'],
      dtype='object')
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['movie_info_idx.id', 'movie_info_idx.movie_id',
       'movie_info_idx.info_type_id'],
      dtype='object')

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/DataPrepare/prepare_single_tables.py:33: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_rows = pd.read_csv(table_obj.csv_file_location, header=None, escapechar='\\', encoding='utf-8',
INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table movie_info
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table movie_info

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_info.id', 'movie_info.movie_id', 'movie_info.info_type_id'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table movie_info
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table movie_info are ['id', 'movie_id', 'info_type_id']
INFO:DataPrepare.prepare_single_tables:NULL values for table movie_info are [-7517860.5001, -1787757.525917082, -100015.73908031239]

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['movie_info.id', 'movie_info.movie_id', 'movie_info.info_type_id'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table movie_info
INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table cast_info

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['cast_info.id', 'cast_info.movie_id', 'cast_info.role_id'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table cast_info
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table cast_info
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table cast_info
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table cast_info are ['id', 'movie_id', 'role_id']
INFO:DataPrepare.prepare_single_tables:NULL values for table cast_info are [-18222172.5001, -1403597.173158533, -100003.6354581403]

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['cast_info.id', 'cast_info.movie_id', 'cast_info.role_id'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table cast_info
INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table movie_keyword
INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table movie_keyword
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table movie_keyword
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table movie_keyword
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table movie_keyword are ['id', 'movie_id', 'keyword_id']
INFO:DataPrepare.prepare_single_tables:NULL values for table movie_keyword are [-2361965.5001, -1959996.4584161101, -113657.74357569481]

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_keyword.id', 'movie_keyword.movie_id',
       'movie_keyword.keyword_id'],
      dtype='object')
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['movie_keyword.id', 'movie_keyword.movie_id',
       'movie_keyword.keyword_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table movie_keyword
INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table movie_companies
INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table movie_companies
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table movie_companies
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table movie_companies
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table movie_companies are ['id', 'movie_id', 'company_id', 'company_type_id']
INFO:DataPrepare.prepare_single_tables:NULL values for table movie_companies are [-1404565.0001, -1750151.1771682862, -133739.30246105613, -100001.51172016136]

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_companies.id', 'movie_companies.movie_id',
       'movie_companies.company_id', 'movie_companies.company_type_id'],
      dtype='object')
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['movie_companies.id', 'movie_companies.movie_id',
       'movie_companies.company_id', 'movie_companies.company_type_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table movie_companies
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 20.6127028465271 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 3448422.0 rows and 9 cols

Discretizing table takes 20.614452838897705 secs

INFO:Models.BN_single_model:Structure learning took 4.098971128463745 secs.
INFO:Models.Bayescard_BN:Model spec[('title.mul_movie_info.movie_id', 'title.production_year'), ('title.mul_movie_info.movie_id', 'title.mul_movie_info_idx.movie_id_nn'), ('title.kind_id', 'title.mul_movie_info.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_cast_info.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_movie_keyword.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_movie_companies.movie_id'), ('title.mul_movie_info_idx.movie_id_nn', 'movie_info_idx.movie_info_idx_nn'), ('title.mul_movie_info_idx.movie_id_nn', 'movie_info_idx.info_type_id')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 4.100238561630249 secs.

INFO:Models.Bayescard_BN:done, took 1.8865253925323486 secs.

done, parameter learning took 1.8877239227294922 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 63.741406202316284 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 14895207.0 rows and 9 cols

Discretizing table takes 63.74298453330994 secs

INFO:Models.BN_single_model:Structure learning took 6.751755952835083 secs.
INFO:Models.Bayescard_BN:Model spec[('movie_info.movie_info_nn', 'movie_info.info_type_id'), ('title.mul_movie_info.movie_id_nn', 'title.kind_id'), ('title.mul_movie_info.movie_id_nn', 'title.production_year'), ('title.mul_movie_info.movie_id_nn', 'title.mul_movie_info_idx.movie_id'), ('movie_info.info_type_id', 'title.mul_movie_info.movie_id_nn'), ('title.mul_movie_info.movie_id_nn', 'title.mul_cast_info.movie_id'), ('title.mul_movie_info.movie_id_nn', 'title.mul_movie_keyword.movie_id'), ('title.mul_movie_info.movie_id_nn', 'title.mul_movie_companies.movie_id')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 6.752824544906616 secs.

INFO:Models.Bayescard_BN:done, took 5.710832118988037 secs.

done, parameter learning took 5.7117674350738525 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 65.34935450553894 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 36441055.0 rows and 9 cols

Discretizing table takes 65.35088443756104 secs

INFO:Models.BN_single_model:Structure learning took 6.111619234085083 secs.
INFO:Models.Bayescard_BN:Model spec[('cast_info.cast_info_nn', 'cast_info.role_id'), ('title.mul_movie_info.movie_id', 'title.kind_id'), ('title.mul_movie_info.movie_id', 'title.production_year'), ('title.mul_movie_info.movie_id', 'title.mul_movie_info_idx.movie_id'), ('title.mul_cast_info.movie_id_nn', 'title.mul_movie_info.movie_id'), ('cast_info.role_id', 'title.mul_cast_info.movie_id_nn'), ('title.mul_movie_info.movie_id', 'title.mul_movie_keyword.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_movie_companies.movie_id')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 6.112682104110718 secs.

INFO:Models.Bayescard_BN:done, took 5.6789727210998535 secs.

done, parameter learning took 5.680211544036865 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 38.83751320838928 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 6575448.0 rows and 9 cols

Discretizing table takes 38.83900594711304 secs

INFO:Models.BN_single_model:Structure learning took 5.596993684768677 secs.
INFO:Models.Bayescard_BN:Model spec[('title.mul_movie_info.movie_id', 'title.production_year'), ('title.mul_movie_info.movie_id', 'title.mul_movie_info_idx.movie_id'), ('title.kind_id', 'title.mul_movie_info.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_cast_info.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_movie_keyword.movie_id_nn'), ('title.mul_movie_info.movie_id', 'title.mul_movie_companies.movie_id'), ('movie_keyword.keyword_id', 'movie_keyword.movie_keyword_nn'), ('title.mul_movie_keyword.movie_id_nn', 'movie_keyword.keyword_id')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 5.598076105117798 secs.

INFO:Models.Bayescard_BN:done, took 3.468351125717163 secs.

done, parameter learning took 3.469681978225708 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 26.711512804031372 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 4050205.0 rows and 10 cols

Discretizing table takes 26.7133526802063 secs

INFO:Models.BN_single_model:Structure learning took 4.99213981628418 secs.
INFO:Models.Bayescard_BN:Model spec[('title.mul_movie_info.movie_id', 'title.production_year'), ('title.mul_movie_info.movie_id', 'title.mul_movie_info_idx.movie_id'), ('title.mul_movie_companies.movie_id_nn', 'title.mul_movie_info.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_cast_info.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_movie_keyword.movie_id'), ('movie_companies.company_type_id', 'title.mul_movie_companies.movie_id_nn'), ('movie_companies.company_type_id', 'movie_companies.movie_companies_nn'), ('title.kind_id', 'movie_companies.company_id'), ('movie_companies.company_id', 'movie_companies.company_type_id')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 4.993334531784058 secs.

INFO:Models.Bayescard_BN:done, took 2.592167377471924 secs.
INFO:test_benchmark:Loaded BN model: 0_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 1_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 2_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 3_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 4_chow-liu_1.pkl
INFO:test_benchmark:Loaded 5 BN models from /home/liwei/starce-final/StarCE/experiment/checkpoint/BayesCard/models/joblight

done, parameter learning took 2.5934388637542725 secs.

WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['title.id', 'title.imdb_index', 'title.kind_id',
       'title.production_year', 'title.phonetic_code', 'title.season_nr',
       'title.episode_nr', 'title.series_years'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table title
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table title
INFO:DataPrepare.prepare_single_tables:Preparing multiplier movie_info_idx.movie_id = title.id for table title

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_info_idx.id', 'movie_info_idx.movie_id',
       'movie_info_idx.info_type_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing multiplier movie_info.movie_id = title.id for table title
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/DataPrepare/prepare_single_tables.py:33: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_rows = pd.read_csv(table_obj.csv_file_location, header=None, escapechar='\\', encoding='utf-8',

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_info.id', 'movie_info.movie_id', 'movie_info.info_type_id'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing multiplier cast_info.movie_id = title.id for table title

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['cast_info.id', 'cast_info.movie_id', 'cast_info.nr_order',
       'cast_info.role_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing multiplier movie_keyword.movie_id = title.id for table title

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_keyword.id', 'movie_keyword.movie_id',
       'movie_keyword.keyword_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing multiplier movie_companies.movie_id = title.id for table title

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_companies.id', 'movie_companies.movie_id',
       'movie_companies.company_id', 'movie_companies.company_type_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table title
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table title are ['id', 'imdb_index', 'kind_id', 'production_year', 'phonetic_code', 'season_nr', 'episode_nr', 'series_years', 'mul_movie_info_idx.movie_id', 'mul_movie_info_idx.movie_id_nn', 'mul_movie_info.movie_id', 'mul_movie_info.movie_id_nn', 'mul_cast_info.movie_id', 'mul_cast_info.movie_id_nn', 'mul_movie_keyword.movie_id', 'mul_movie_keyword.movie_id_nn', 'mul_movie_companies.movie_id', 'mul_movie_companies.movie_id_nn']
INFO:DataPrepare.prepare_single_tables:NULL values for table title are [-1364156.5001, -100001.89081599863, -100004.94392536649, -101992.78876199525, -1146947.8223354327, -100003.73430075865, -100313.81798239263, 0, -100000.54593255547, -100001.36402264879, -100005.86793593164, -100005.89146427783, -100014.33549215097, -100014.41329544423, -100001.78940843978, -100002.60082649262, -100001.03206480498, -100001.60204034597]

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['title.id', 'title.imdb_index', 'title.kind_id',
       'title.production_year', 'title.phonetic_code', 'title.season_nr',
       'title.episode_nr', 'title.series_years',
       'title.mul_movie_info_idx.movie_id',
       'title.mul_movie_info_idx.movie_id_nn', 'title.mul_movie_info.movie_id',
       'title.mul_movie_info.movie_id_nn', 'title.mul_cast_info.movie_id',
       'title.mul_cast_info.movie_id_nn', 'title.mul_movie_keyword.movie_id',
       'title.mul_movie_keyword.movie_id_nn',
       'title.mul_movie_companies.movie_id',
       'title.mul_movie_companies.movie_id_nn'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table title
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table title and relationship movie_info_idx.movie_id = title.id

====================================
Index(['title.id', 'title.imdb_index', 'title.kind_id',
       'title.production_year', 'title.phonetic_code', 'title.season_nr',
       'title.episode_nr', 'title.series_years',
       'title.mul_movie_info_idx.movie_id',
       'title.mul_movie_info_idx.movie_id_nn', 'title.mul_movie_info.movie_id',
       'title.mul_movie_info.movie_id_nn', 'title.mul_cast_info.movie_id',
       'title.mul_cast_info.movie_id_nn', 'title.mul_movie_keyword.movie_id',
       'title.mul_movie_keyword.movie_id_nn',
       'title.mul_movie_companies.movie_id',
       'title.mul_movie_companies.movie_id_nn'],
      dtype='object') title.id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_info_idx.id', 'movie_info_idx.movie_id',
       'movie_info_idx.info_type_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table title and relationship movie_info.movie_id = title.id

====================================
Index(['title.id', 'title.imdb_index', 'title.kind_id',
       'title.production_year', 'title.phonetic_code', 'title.season_nr',
       'title.episode_nr', 'title.series_years',
       'title.mul_movie_info_idx.movie_id',
       'title.mul_movie_info_idx.movie_id_nn', 'title.mul_movie_info.movie_id',
       'title.mul_movie_info.movie_id_nn', 'title.mul_cast_info.movie_id',
       'title.mul_cast_info.movie_id_nn', 'title.mul_movie_keyword.movie_id',
       'title.mul_movie_keyword.movie_id_nn',
       'title.mul_movie_companies.movie_id',
       'title.mul_movie_companies.movie_id_nn'],
      dtype='object') title.id

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/DataPrepare/prepare_single_tables.py:33: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_rows = pd.read_csv(table_obj.csv_file_location, header=None, escapechar='\\', encoding='utf-8',

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_info.id', 'movie_info.movie_id', 'movie_info.info_type_id'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table title and relationship cast_info.movie_id = title.id

====================================
Index(['title.id', 'title.imdb_index', 'title.kind_id',
       'title.production_year', 'title.phonetic_code', 'title.season_nr',
       'title.episode_nr', 'title.series_years',
       'title.mul_movie_info_idx.movie_id',
       'title.mul_movie_info_idx.movie_id_nn', 'title.mul_movie_info.movie_id',
       'title.mul_movie_info.movie_id_nn', 'title.mul_cast_info.movie_id',
       'title.mul_cast_info.movie_id_nn', 'title.mul_movie_keyword.movie_id',
       'title.mul_movie_keyword.movie_id_nn',
       'title.mul_movie_companies.movie_id',
       'title.mul_movie_companies.movie_id_nn'],
      dtype='object') title.id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['cast_info.id', 'cast_info.movie_id', 'cast_info.nr_order',
       'cast_info.role_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table title and relationship movie_keyword.movie_id = title.id

====================================
Index(['title.id', 'title.imdb_index', 'title.kind_id',
       'title.production_year', 'title.phonetic_code', 'title.season_nr',
       'title.episode_nr', 'title.series_years',
       'title.mul_movie_info_idx.movie_id',
       'title.mul_movie_info_idx.movie_id_nn', 'title.mul_movie_info.movie_id',
       'title.mul_movie_info.movie_id_nn', 'title.mul_cast_info.movie_id',
       'title.mul_cast_info.movie_id_nn', 'title.mul_movie_keyword.movie_id',
       'title.mul_movie_keyword.movie_id_nn',
       'title.mul_movie_companies.movie_id',
       'title.mul_movie_companies.movie_id_nn'],
      dtype='object') title.id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_keyword.id', 'movie_keyword.movie_id',
       'movie_keyword.keyword_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table title and relationship movie_companies.movie_id = title.id

====================================
Index(['title.id', 'title.imdb_index', 'title.kind_id',
       'title.production_year', 'title.phonetic_code', 'title.season_nr',
       'title.episode_nr', 'title.series_years',
       'title.mul_movie_info_idx.movie_id',
       'title.mul_movie_info_idx.movie_id_nn', 'title.mul_movie_info.movie_id',
       'title.mul_movie_info.movie_id_nn', 'title.mul_cast_info.movie_id',
       'title.mul_cast_info.movie_id_nn', 'title.mul_movie_keyword.movie_id',
       'title.mul_movie_keyword.movie_id_nn',
       'title.mul_movie_companies.movie_id',
       'title.mul_movie_companies.movie_id_nn'],
      dtype='object') title.id
!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_companies.id', 'movie_companies.movie_id',
       'movie_companies.company_id', 'movie_companies.company_type_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table movie_info_idx
INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table movie_info_idx
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table movie_info_idx
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table movie_info_idx
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table movie_info_idx are ['id', 'movie_id', 'info_type_id']
INFO:DataPrepare.prepare_single_tables:NULL values for table movie_info_idx are [-790018.0001, -1691796.733549514, -100100.00236805841]
INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table movie_info_idx
INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table movie_info

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_info_idx.id', 'movie_info_idx.movie_id',
       'movie_info_idx.info_type_id'],
      dtype='object')
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['movie_info_idx.id', 'movie_info_idx.movie_id',
       'movie_info_idx.info_type_id'],
      dtype='object')

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/DataPrepare/prepare_single_tables.py:33: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_rows = pd.read_csv(table_obj.csv_file_location, header=None, escapechar='\\', encoding='utf-8',

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_info.id', 'movie_info.movie_id', 'movie_info.info_type_id'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table movie_info
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table movie_info
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table movie_info
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table movie_info are ['id', 'movie_id', 'info_type_id']
INFO:DataPrepare.prepare_single_tables:NULL values for table movie_info are [-7517860.5001, -1787757.525917082, -100015.73908031239]

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['movie_info.id', 'movie_info.movie_id', 'movie_info.info_type_id'], dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table movie_info
INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table cast_info

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['cast_info.id', 'cast_info.movie_id', 'cast_info.nr_order',
       'cast_info.role_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table cast_info
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table cast_info
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table cast_info
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table cast_info are ['id', 'movie_id', 'nr_order', 'role_id']
INFO:DataPrepare.prepare_single_tables:NULL values for table cast_info are [-18222172.5001, -1403597.173158533, -106697.79546682973, -100003.6354581403]

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['cast_info.id', 'cast_info.movie_id', 'cast_info.nr_order',
       'cast_info.role_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table cast_info
INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table movie_keyword
INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table movie_keyword
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table movie_keyword
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table movie_keyword
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table movie_keyword are ['id', 'movie_id', 'keyword_id']
INFO:DataPrepare.prepare_single_tables:NULL values for table movie_keyword are [-2361965.5001, -1959996.4584161101, -113657.74357569481]

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_keyword.id', 'movie_keyword.movie_id',
       'movie_keyword.keyword_id'],
      dtype='object')
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['movie_keyword.id', 'movie_keyword.movie_id',
       'movie_keyword.keyword_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table movie_keyword
INFO:DataPrepare.prepare_single_tables:Preparing hdf file for table movie_companies
INFO:DataPrepare.prepare_single_tables:Managing functional dependencies for table movie_companies
INFO:DataPrepare.prepare_single_tables:Preparing multipliers for table movie_companies
INFO:DataPrepare.prepare_single_tables:Preparing categorical values and null values for table movie_companies
INFO:DataPrepare.prepare_single_tables:Relevant attributes for table movie_companies are ['id', 'movie_id', 'company_id', 'company_type_id']
INFO:DataPrepare.prepare_single_tables:NULL values for table movie_companies are [-1404565.0001, -1750151.1771682862, -133739.30246105613, -100001.51172016136]

!!!!!!!!!!!!!!!!!!!!!!!!!
Index(['movie_companies.id', 'movie_companies.movie_id',
       'movie_companies.company_id', 'movie_companies.company_type_id'],
      dtype='object')
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
[] Index(['movie_companies.id', 'movie_companies.movie_id',
       'movie_companies.company_id', 'movie_companies.company_type_id'],
      dtype='object')

INFO:DataPrepare.prepare_single_tables:Adding table parts without join partners for table movie_companies
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 29.963947296142578 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 3448422.0 rows and 14 cols

Discretizing table takes 29.965687036514282 secs

INFO:Models.BN_single_model:Structure learning took 7.820193529129028 secs.
INFO:Models.Bayescard_BN:Model spec[('title.imdb_index', 'title.kind_id'), ('title.mul_movie_info.movie_id', 'title.production_year'), ('title.mul_movie_info.movie_id', 'title.phonetic_code'), ('title.kind_id', 'title.season_nr'), ('title.season_nr', 'title.episode_nr'), ('title.kind_id', 'title.series_years'), ('title.mul_movie_info.movie_id', 'title.mul_movie_info_idx.movie_id_nn'), ('title.kind_id', 'title.mul_movie_info.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_cast_info.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_movie_keyword.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_movie_companies.movie_id'), ('title.mul_movie_info_idx.movie_id_nn', 'movie_info_idx.movie_info_idx_nn'), ('title.mul_movie_info_idx.movie_id_nn', 'movie_info_idx.info_type_id')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 7.8215012550354 secs.

INFO:Models.Bayescard_BN:done, took 2.939250946044922 secs.

done, parameter learning took 2.9405574798583984 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 91.23502540588379 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 14895207.0 rows and 14 cols

Discretizing table takes 91.2369396686554 secs

INFO:Models.BN_single_model:Structure learning took 10.231949090957642 secs.
INFO:Models.Bayescard_BN:Model spec[('movie_info.movie_info_nn', 'movie_info.info_type_id'), ('title.production_year', 'title.imdb_index'), ('title.mul_movie_info.movie_id_nn', 'title.kind_id'), ('title.series_years', 'title.production_year'), ('title.mul_movie_info.movie_id_nn', 'title.phonetic_code'), ('title.kind_id', 'title.season_nr'), ('title.season_nr', 'title.episode_nr'), ('title.kind_id', 'title.series_years'), ('title.mul_movie_info.movie_id_nn', 'title.mul_movie_info_idx.movie_id'), ('movie_info.info_type_id', 'title.mul_movie_info.movie_id_nn'), ('title.mul_movie_info.movie_id_nn', 'title.mul_cast_info.movie_id'), ('title.mul_movie_info.movie_id_nn', 'title.mul_movie_keyword.movie_id'), ('title.mul_movie_info.movie_id_nn', 'title.mul_movie_companies.movie_id')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 10.232985973358154 secs.

INFO:Models.Bayescard_BN:done, took 9.473742961883545 secs.

done, parameter learning took 9.475054025650024 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 114.83612394332886 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 36441055.0 rows and 15 cols

Discretizing table takes 114.83795142173767 secs

INFO:Models.BN_single_model:Structure learning took 10.678588628768921 secs.
INFO:Models.Bayescard_BN:Model spec[('cast_info.role_id', 'cast_info.nr_order'), ('cast_info.cast_info_nn', 'cast_info.role_id'), ('title.kind_id', 'title.imdb_index'), ('title.mul_movie_info.movie_id', 'title.kind_id'), ('title.mul_movie_info.movie_id', 'title.production_year'), ('title.mul_movie_info.movie_id', 'title.phonetic_code'), ('title.kind_id', 'title.season_nr'), ('title.season_nr', 'title.episode_nr'), ('title.kind_id', 'title.series_years'), ('title.mul_movie_info.movie_id', 'title.mul_movie_info_idx.movie_id'), ('title.mul_cast_info.movie_id_nn', 'title.mul_movie_info.movie_id'), ('cast_info.nr_order', 'title.mul_cast_info.movie_id_nn'), ('title.mul_movie_info.movie_id', 'title.mul_movie_keyword.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_movie_companies.movie_id')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 10.679898500442505 secs.

INFO:Models.Bayescard_BN:done, took 9.441300630569458 secs.

done, parameter learning took 9.442321538925171 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 60.26357412338257 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 6575448.0 rows and 14 cols

Discretizing table takes 60.26547980308533 secs

INFO:Models.BN_single_model:Structure learning took 8.853811025619507 secs.
INFO:Models.Bayescard_BN:Model spec[('title.mul_movie_info.movie_id', 'title.kind_id'), ('title.mul_movie_info.movie_id', 'title.production_year'), ('title.mul_movie_info.movie_id', 'title.phonetic_code'), ('title.kind_id', 'title.season_nr'), ('title.season_nr', 'title.episode_nr'), ('title.kind_id', 'title.series_years'), ('title.mul_movie_info.movie_id', 'title.mul_movie_info_idx.movie_id'), ('title.imdb_index', 'title.mul_movie_info.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_cast_info.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_movie_keyword.movie_id_nn'), ('title.mul_movie_info.movie_id', 'title.mul_movie_companies.movie_id'), ('movie_keyword.keyword_id', 'movie_keyword.movie_keyword_nn'), ('title.mul_movie_keyword.movie_id_nn', 'movie_keyword.keyword_id')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 8.855143785476685 secs.

INFO:Models.Bayescard_BN:done, took 5.417415380477905 secs.

done, parameter learning took 5.418384552001953 secs.

/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
/home/liwei/starce-final/StarCE/methods/SafeBound/bayescard/Models/tools.py:26: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.
  for i, (val, freq) in enumerate(value_counts.iteritems()):
INFO:Models.BN_single_model:Discretizing table takes 36.66057229042053 secs
INFO:Models.BN_single_model:Learning BN optimal structure from data with 4050205.0 rows and 15 cols

Discretizing table takes 36.66246151924133 secs

INFO:Models.BN_single_model:Structure learning took 8.455171823501587 secs.
INFO:Models.Bayescard_BN:Model spec[('title.imdb_index', 'title.kind_id'), ('title.mul_movie_info.movie_id', 'title.production_year'), ('movie_companies.company_id', 'title.phonetic_code'), ('title.kind_id', 'title.season_nr'), ('title.season_nr', 'title.episode_nr'), ('title.kind_id', 'title.series_years'), ('title.mul_movie_info.movie_id', 'title.mul_movie_info_idx.movie_id'), ('title.mul_movie_companies.movie_id_nn', 'title.mul_movie_info.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_cast_info.movie_id'), ('title.mul_movie_info.movie_id', 'title.mul_movie_keyword.movie_id'), ('movie_companies.company_type_id', 'title.mul_movie_companies.movie_id_nn'), ('movie_companies.company_type_id', 'movie_companies.movie_companies_nn'), ('title.kind_id', 'movie_companies.company_id'), ('movie_companies.company_id', 'movie_companies.company_type_id')]
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
INFO:Models.Bayescard_BN:calling pgm.BayesianModel.fit...

Structure learning took 8.456488609313965 secs.

INFO:Models.Bayescard_BN:done, took 3.63533616065979 secs.
INFO:test_benchmark:Loaded BN model: 0_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 1_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 2_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 3_chow-liu_1.pkl
INFO:test_benchmark:Loaded BN model: 4_chow-liu_1.pkl
INFO:test_benchmark:Loaded 5 BN models from /home/liwei/starce-final/StarCE/experiment/checkpoint/BayesCard/models/joblightranges

done, parameter learning took 3.636654853820801 secs.

WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.
WARNING:pgmpy:BayesianModel has been renamed to BayesianNetwork. Please use BayesianNetwork class, BayesianModel will be removed in future.

,benchmark,seed,preprocess_time_sec,train_time_sec,total_build_like_time_sec,total_eval_like_time_sec,query_count,avg_latency_sec,checkpoint_output,model_dir,statistics_size_bytes
0,STATS,0,28.03348,114.880966,142.914446,40.207078,2471,0.013303,/home/liwei/starce-final/StarCE/experiment/che...,/home/liwei/starce-final/StarCE/experiment/che...,6326548
1,JOBLight,0,0.00000,724.880644,724.880644,3.081380,451,0.004361,/home/liwei/starce-final/StarCE/experiment/che...,/home/liwei/starce-final/StarCE/experiment/che...,1630079
2,JOBLightRanges,0,33.53912,1014.735962,1048.275082,70.893444,8292,0.006208,/home/liwei/starce-final/StarCE/experiment/che...,/home/liwei/starce-final/StarCE/experiment/che...,2309697
3,STATSJOIN,0,0.00000,0.000000,0.000000,2.455658,226,0.008057,/home/liwei/starce-final/StarCE/experiment/che...,/home/liwei/starce-final/StarCE/experiment/che...,6326548

In [4]:
summary_csv = CHECKPOINT_DIR / 'benchmark_times.csv'
summary_df = pd.read_csv(summary_csv)

print(f'Summary CSV: {summary_csv}')
for _, row in summary_df.iterrows():
    print(f"{row['benchmark']}: card={row['checkpoint_output']}, eval_time={row['total_eval_like_time_sec']}")

summary_df

Summary CSV: /home/liwei/starce-final/StarCE/experiment/checkpoint/BayesCard/benchmark_times.csv
STATS: card=/home/liwei/starce-final/StarCE/experiment/checkpoint/BayesCard/card_stats.txt, eval_time=40.20707845687866
JOBLight: card=/home/liwei/starce-final/StarCE/experiment/checkpoint/BayesCard/card_joblight.txt, eval_time=3.0813801288604736
JOBLightRanges: card=/home/liwei/starce-final/StarCE/experiment/checkpoint/BayesCard/card_joblr.txt, eval_time=70.89344382286072
STATSJOIN: card=/home/liwei/starce-final/StarCE/experiment/checkpoint/BayesCard/card_statsjoin.txt, eval_time=2.455657958984375

,benchmark,total_eval_like_time_sec,checkpoint_output,train_time_sec,total_build_like_time_sec,preprocess_time_sec,query_count,avg_latency_sec,model_dir,statistics_size_bytes,seed
0,STATS,40.207078,/home/liwei/starce-final/StarCE/experiment/che...,114.880966,142.914446,28.03348,2471,0.013303,/home/liwei/starce-final/StarCE/experiment/che...,6326548,0
1,JOBLight,3.081380,/home/liwei/starce-final/StarCE/experiment/che...,724.880644,724.880644,0.00000,451,0.004361,/home/liwei/starce-final/StarCE/experiment/che...,1630079,0
2,JOBLightRanges,70.893444,/home/liwei/starce-final/StarCE/experiment/che...,1014.735962,1048.275082,33.53912,8292,0.006208,/home/liwei/starce-final/StarCE/experiment/che...,2309697,0
3,STATSJOIN,2.455658,/home/liwei/starce-final/StarCE/experiment/che...,0.000000,0.000000,0.00000,226,0.008057,/home/liwei/starce-final/StarCE/experiment/che...,6326548,0